import "./globals.css";
import Header from "@/Components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="br">
      <body>
        <div>
          <Header />
        </div>
        <div className="container p-4">{children}</div>
      </body>
    </html>
  );
}
