import type { Metadata } from "next";
import Header from "@/Components/Header";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PrincipalLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="flex">
        <div>
          <Header />
        </div>
        <div className="pl-3 flex w-full">{children}</div>
      </body>
    </html>
  );
}
